#######################################
#
# NBI-Online的各种外部配置项
#
#######################################

#######################################
#
# MongoDB
#
#######################################
db_user: root
db_password: buptweb007
db_address: 49.232.229.126
db_port: 27017
db_authsource: admin

#######################################
#
# Image GC
#
#######################################

# hours
gc_interval: 24

#True or False
gc_mode: False

# Default expire time for unprocessed image (hours)
gc_unprocessed_image_expire_time: 24


########################################
#
# Image Process
#
########################################

# Image compress threshold
image_temp_compress_threshold: 500000

image_storage_compress_threshold: 300000